name: Run Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t countries-dashboard .

      - name: Run tests
        run: docker run --rm countries-dashboard npm test -- --watchAll=false
